#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[vars]
BASE_PATH = "/ai-editor"

# Route configuration to ensure proper asset serving with base path
[[pages.rules]]
pattern = "/ai-editor/*"
priority = 100

[[pages.rules]]
pattern = "/ai-editor/assets/*"
priority = 200

[[pages.rules]]
pattern = "/ai-editor/build/*" 
priority = 200
